In [ ]:

###Code provided by Sir
import re
import pandas as pd

# --------------------------------------------------
# Read Dataset
# --------------------------------------------------

df = pd.read_csv(r"D:\NLP\resumes.csv")

print("Original Dataset\n")
print(df)

# --------------------------------------------------
# TextCleaner Class
# --------------------------------------------------

class TextCleaner:

    # Extract Email
    def extract_email(self, text):

        emails = re.findall(r'[\w\.-]+@[\w\.-]+\.\w+', text)

        return ", ".join(emails)

    # Extract URL
    def extract_url(self, text):

        urls = re.findall(r'https?://\S+', text)

        return ", ".join(urls)

    # Extract Phone Number
    def extract_phone(self, text):

        phones = re.findall(r'(\+?\d[\d\-\(\)\s]{8,}\d)', text)

        cleaned = []

        for phone in phones:

            number = re.sub(r'\D', '', phone)

            cleaned.append(number)

        return ", ".join(cleaned)

    # Extract Hashtags
    def extract_hashtag(self, text):

        hashtags = re.findall(r'#(\w+)', text)

        return ", ".join(hashtags)

    # Remove HTML Tags
    def remove_html(self, text):

        return re.sub(r'<.*?>', '', text)

    # Remove JSON Tags
    def remove_json(self, text):

        return re.sub(r'\{.*?\}', '', text)

    # Extract Experience
    def extract_experience(self, text):

        match = re.search(r'(\d+)\s+years', text, re.I)

        if match:

            return match.group(1)

        return ""

    # Extract Name
    def extract_name(self, text):

        words = text.split()

        return " ".join(words[:2])

    # Extract Skills
    def extract_skills(self, text):

        skills = ['Python','Java','SQL','Machine Learning',
                  'Data Science','AI','NLP',
                  'Deep Learning','React','HTML','JavaScript']

        found = []

        for skill in skills:

            if skill.lower() in text.lower():

                found.append(skill)

        return ", ".join(found)

# --------------------------------------------------

cleaner = TextCleaner()

# --------------------------------------------------
# Apply Functions
# --------------------------------------------------

df["Name"] = df["resume"].apply(cleaner.extract_name)

df["Email"] = df["resume"].apply(cleaner.extract_email)

df["Phone"] = df["resume"].apply(cleaner.extract_phone)

df["Experience"] = df["resume"].apply(cleaner.extract_experience)

df["Skills"] = df["resume"].apply(cleaner.extract_skills)

df["URL"] = df["resume"].apply(cleaner.extract_url)

df["Hashtags"] = df["resume"].apply(cleaner.extract_hashtag)

# Remove HTML

df["Clean_Text"] = df["resume"].apply(cleaner.remove_html)

# Remove JSON

df["Clean_Text"] = df["Clean_Text"].apply(cleaner.remove_json)

# --------------------------------------------------
# Display Results
# --------------------------------------------------

print("\n\nExtracted Information\n")

print(df[["Name",
          "Email",
          "Phone",
          "Experience",
          "Skills",
          "URL",
          "Hashtags"]])

# --------------------------------------------------
# Save CSV
# --------------------------------------------------

df.to_csv("extracted_resume_data.csv", index=False)

print("\nData Saved Successfully!")

Original Dataset

   id                                             resume
0   1  John Smith Email: johnsmith@gmail.com Phone: +...
1   2  Alice Johnson alice@yahoo.com Mobile: 98765 12...
2   3  Rahul Sharma Email: rahul123@gmail.com Phone: ...
3   4  Emma Brown Contact: emma.brown@company.org Mob...


Extracted Information

            Name                   Email         Phone Experience  \
0     John Smith     johnsmith@gmail.com  919876543210          5
1  Alice Johnson         alice@yahoo.com    9876512345          3
2   Rahul Sharma      rahul123@gmail.com    9876543210          8
3     Emma Brown  emma.brown@company.org   15552349876         10

                                 Skills                                URL  \
0                 Python, Java, SQL, AI  https://linkedin.com/in/johnsmith
1  Machine Learning, Data Science, HTML
2                AI, NLP, Deep Learning
3         Java, React, HTML, JavaScript

  Hashtags
0
1
2  AI, NLP
3

Data Saved Successfully!

In [3]:
import re
import pandas as pd

df = pd.read_csv(r"D:\NLP\resumes.csv")

print("Original Dataset:")
display(df)

Original Dataset:

   id                                             resume
0   1  John Smith Email: johnsmith@gmail.com Phone: +...
1   2  Alice Johnson alice@yahoo.com Mobile: 98765 12...
2   3  Rahul Sharma Email: rahul123@gmail.com Phone: ...
3   4  Emma Brown Contact: emma.brown@company.org Mob...

In [4]:
class ResumeParser:

    def email(self, text):
        return ", ".join(re.findall(r'[\w.-]+@[\w.-]+\.\w+', str(text)))

    def phone(self, text):
        nums = re.findall(r'\+?\d[\d\s().-]{8,}\d', str(text))
        return ", ".join(re.sub(r'\D', '', n) for n in nums)

    def url(self, text):
        return ", ".join(re.findall(r'https?://\S+', str(text)))

    def hashtag(self, text):
        return ", ".join(re.findall(r'#(\w+)', str(text)))

    def experience(self, text):
        result = re.search(r'(\d+)\s+years?', str(text), re.I)
        return result.group(1) if result else ""

    def name(self, text):
        return " ".join(str(text).split()[:2])

    def skills(self, text):
        skill_set = [
            "Python", "Java", "SQL", "Machine Learning",
            "Data Science", "AI", "NLP", "Deep Learning",
            "React", "HTML", "JavaScript"
        ]
        text = str(text).lower()
        return ", ".join(s for s in skill_set if s.lower() in text)

    def clean(self, text):
        text = re.sub(r'<.*?>', '', str(text))
        return re.sub(r'\{.*?\}', '', text)

In [5]:
parser = ResumeParser()

df["Name"] = df.resume.map(parser.name)
df["Email"] = df.resume.map(parser.email)
df["Phone"] = df.resume.map(parser.phone)
df["Experience"] = df.resume.map(parser.experience)
df["Skills"] = df.resume.map(parser.skills)
df["URL"] = df.resume.map(parser.url)
df["Hashtags"] = df.resume.map(parser.hashtag)
df["Clean_Text"] = df.resume.map(parser.clean)

result = df[[
    "Name", "Email", "Phone", "Experience",
    "Skills", "URL", "Hashtags", "Clean_Text"
]]

display(result)

,Name,Email,Phone,Experience,Skills,URL,Hashtags,Clean_Text
0,John Smith,johnsmith@gmail.com,919876543210,5,"Python, Java, SQL, AI",https://linkedin.com/in/johnsmith,,John Smith Email: johnsmith@gmail.com Phone: +...
1,Alice Johnson,alice@yahoo.com,9876512345,3,"Machine Learning, Data Science, HTML",,,Alice Johnson alice@yahoo.com Mobile: 98765 12...
2,Rahul Sharma,rahul123@gmail.com,9876543210,8,"AI, NLP, Deep Learning",,"AI, NLP",Rahul Sharma Email: rahul123@gmail.com Phone: ...
3,Emma Brown,emma.brown@company.org,15552349876,10,"Java, React, HTML, JavaScript",,,Emma Brown Contact: emma.brown@company.org Mob...

In [6]:
print("=" * 80)
print("             RESUME INFORMATION EXTRACTION REPORT")
print("=" * 80)

print(f"Total Resumes Processed : {len(df)}")
print(f"Columns Extracted       : {len(result.columns)}")

print("\nExtracted Fields:")
print("-" * 80)

display(result)

result.to_csv(r"D:\NLP\extracted_resume_data.csv", index=False)

print("\n" + "=" * 80)
print("Report Generated Successfully!")
print("File: D:\\NLP\\extracted_resume_data.csv")
print("=" * 80)

================================================================================
             RESUME INFORMATION EXTRACTION REPORT
================================================================================
Total Resumes Processed : 4
Columns Extracted       : 8

Extracted Fields:
--------------------------------------------------------------------------------

,Name,Email,Phone,Experience,Skills,URL,Hashtags,Clean_Text
0,John Smith,johnsmith@gmail.com,919876543210,5,"Python, Java, SQL, AI",https://linkedin.com/in/johnsmith,,John Smith Email: johnsmith@gmail.com Phone: +...
1,Alice Johnson,alice@yahoo.com,9876512345,3,"Machine Learning, Data Science, HTML",,,Alice Johnson alice@yahoo.com Mobile: 98765 12...
2,Rahul Sharma,rahul123@gmail.com,9876543210,8,"AI, NLP, Deep Learning",,"AI, NLP",Rahul Sharma Email: rahul123@gmail.com Phone: ...
3,Emma Brown,emma.brown@company.org,15552349876,10,"Java, React, HTML, JavaScript",,,Emma Brown Contact: emma.brown@company.org Mob...

================================================================================
Report Generated Successfully!
File: D:\NLP\extracted_resume_data.csv
================================================================================