In [1]:
import pandas as pd
import nltk
import spacy

In [2]:
nlp = spacy.load("en_core_web_sm")
print("spaCy model loaded successfully!")

spaCy model loaded successfully!

In [4]:
df = pd.read_csv(r"D:\NLP\sample.csv")
df

   id                                            text
0   1           OMG!!! 😍 India won the match today!!!
1   2      Breaking News: Heavy rain in Mumbai today.
2   3                           मैं आज बहुत खुश हूँ 😊
3   4                        This movie is awesome 😂😂
4   5  RT @user Fake news spreads quickly on Twitter!
5   6         Visit https://abc.com for more updates.
6   7                       भारत won the मैच today 😂🔥
7   8             Reddit users say this is fake news!

In [5]:
text = "I love India"

tokens = text.split()

print("Whitespace Tokenization:")
print(tokens)

Whitespace Tokenization:
['I', 'love', 'India']

In [6]:
from nltk.tokenize import word_tokenize

text = "I love India."

tokens = word_tokenize(text)

print("NLTK Tokenization:")
print(tokens)

NLTK Tokenization:
['I', 'love', 'India', '.']

In [7]:
text = "I love India."

doc = nlp(text)

print("spaCy Tokenization:")

for token in doc:
    print(token.text)

spaCy Tokenization:
I
love
India
.

In [8]:
from nltk.tokenize import word_tokenize

text = "I love India."

print("Original Text:")
print(text)

print("\nWhitespace Tokenization:")
print(text.split())

print("\nNLTK Tokenization:")
print(word_tokenize(text))

print("\nspaCy Tokenization:")
doc = nlp(text)
print([token.text for token in doc])

Original Text:
I love India.

Whitespace Tokenization:
['I', 'love', 'India.']

NLTK Tokenization:
['I', 'love', 'India', '.']

spaCy Tokenization:
['I', 'love', 'India', '.']

In [9]:
import re

In [10]:
def clean_text(text):

    # Convert to string
    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove Twitter mentions
    text = re.sub(r"@\w+", "", text)

    # Remove hashtag symbol
    text = re.sub(r"#", "", text)

    # Remove emojis
    text = re.sub(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "]+",
        "",
        text,
    )

    # Remove punctuation
    text = re.sub(r"[^\w\s]", "", text)

    return text

In [11]:
df["Clean_Text"] = df["text"].apply(clean_text)

df[["text", "Clean_Text"]]

,text,Clean_Text
0,OMG!!! 😍 India won the match today!!!,omg india won the match today
1,Breaking News: Heavy rain in Mumbai today.,breaking news heavy rain in mumbai today
2,मैं आज बहुत खुश हूँ 😊,म आज बहत खश ह
3,This movie is awesome 😂😂,this movie is awesome
4,RT @user Fake news spreads quickly on Twitter!,rt fake news spreads quickly on twitter
5,Visit https://abc.com for more updates.,visit for more updates
6,भारत won the मैच today 😂🔥,भरत won the मच today
7,Reddit users say this is fake news!,reddit users say this is fake news

In [12]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [13]:
stop_words = set(stopwords.words("english"))

print(stop_words)

{"didn't", 'who', 'because', 'his', 'again', "you'll", 'did', 'off', 'at', 'was', 'herself', 'it', "hadn't", "couldn't", 'up', 'are', 'me', 'for', 'now', 'am', 'shouldn', "we've", 'have', 'needn', 'then', 'when', 'hers', 'and', 'further', 'such', 'over', 'of', 't', "wouldn't", 'ain', 'doing', 'between', 'own', 'weren', 'few', 'ours', 'didn', 'm', 'with', 'before', "needn't", "she'd", "it's", 'ma', 'we', 'an', 'all', 'won', 'its', 'just', 'each', 're', "they're", 'or', 'her', 'most', 'once', "we'll", "they'll", "mustn't", 'from', 'is', 'mustn', "she's", 'until', "we're", 'too', 'nor', 'aren', "i've", 'if', 'to', 'during', 'been', 'any', 'shan', 'ourselves', 'he', 'there', 'those', 'very', 'as', "hasn't", 'them', 'more', 'in', 'their', 'you', 'not', "i'll", "he's", "it'd", "i'm", "they've", 'yours', "she'll", 'isn', 'my', "haven't", 've', 'hadn', 'than', 'about', "isn't", 'same', "he'd", "aren't", 'yourself', 'don', 'should', 'does', 'will', 'wouldn', 'y', 'but', 'himself', 'where', "you'd", 'they', 'under', 'mightn', 'after', 'other', 'no', 'o', 'so', 'by', "i'd", 'couldn', 'while', "you're", 'wasn', "wasn't", "they'd", 'd', "shouldn't", 's', 'being', "doesn't", 'both', 'theirs', 'that', 'i', 'haven', 'this', 'yourselves', 'how', 'can', "it'll", "mightn't", 'do', "he'll", 'into', 'only', 'themselves', 'which', "we'd", 'itself', 'what', "should've", 'out', 'why', 'she', 'a', 'whom', 'down', "that'll", "weren't", 'on', 'these', "don't", 'the', 'hasn', 'through', 'were', 'll', 'your', 'above', 'doesn', 'having', 'him', 'myself', 'here', "won't", 'against', 'had', "you've", 'below', 'some', 'our', 'be', "shan't", 'has'}

In [14]:
def remove_stopwords(sentence):

    words = word_tokenize(sentence)

    filtered = []

    for word in words:
        if word not in stop_words:
            filtered.append(word)

    return filtered

In [15]:
df["Stopword_Removal"] = df["Clean_Text"].apply(remove_stopwords)

df[["Clean_Text", "Stopword_Removal"]]

,Clean_Text,Stopword_Removal
0,omg india won the match today,"[omg, india, match, today]"
1,breaking news heavy rain in mumbai today,"[breaking, news, heavy, rain, mumbai, today]"
2,म आज बहत खश ह,"[म, आज, बहत, खश, ह]"
3,this movie is awesome,"[movie, awesome]"
4,rt fake news spreads quickly on twitter,"[rt, fake, news, spreads, quickly, twitter]"
5,visit for more updates,"[visit, updates]"
6,भरत won the मच today,"[भरत, मच, today]"
7,reddit users say this is fake news,"[reddit, users, say, fake, news]"

In [16]:
from nltk.stem import PorterStemmer
porter = PorterStemmer()
def porter_stem(words):
    return [porter.stem(word) for word in words]

In [18]:
print(df.columns)

Index(['id', 'text', 'Clean_Text', 'Stopword_Removal', 'Snowball_Stem'], dtype='object')

In [19]:
from nltk.stem import PorterStemmer

porter = PorterStemmer()

def porter_stem(words):
    return [porter.stem(word) for word in words]

df["Porter_Stem"] = df["Stopword_Removal"].apply(porter_stem)

df[["Stopword_Removal", "Porter_Stem"]]

,Stopword_Removal,Porter_Stem
0,"[omg, india, match, today]","[omg, india, match, today]"
1,"[breaking, news, heavy, rain, mumbai, today]","[break, news, heavi, rain, mumbai, today]"
2,"[म, आज, बहत, खश, ह]","[म, आज, बहत, खश, ह]"
3,"[movie, awesome]","[movi, awesom]"
4,"[rt, fake, news, spreads, quickly, twitter]","[rt, fake, news, spread, quickli, twitter]"
5,"[visit, updates]","[visit, updat]"
6,"[भरत, मच, today]","[भरत, मच, today]"
7,"[reddit, users, say, fake, news]","[reddit, user, say, fake, news]"

In [20]:
df[["Stopword_Removal", "Porter_Stem", "Snowball_Stem"]]

,Stopword_Removal,Porter_Stem,Snowball_Stem
0,"[omg, india, match, today]","[omg, india, match, today]","[omg, india, match, today]"
1,"[breaking, news, heavy, rain, mumbai, today]","[break, news, heavi, rain, mumbai, today]","[break, news, heavi, rain, mumbai, today]"
2,"[म, आज, बहत, खश, ह]","[म, आज, बहत, खश, ह]","[म, आज, बहत, खश, ह]"
3,"[movie, awesome]","[movi, awesom]","[movi, awesom]"
4,"[rt, fake, news, spreads, quickly, twitter]","[rt, fake, news, spread, quickli, twitter]","[rt, fake, news, spread, quick, twitter]"
5,"[visit, updates]","[visit, updat]","[visit, updat]"
6,"[भरत, मच, today]","[भरत, मच, today]","[भरत, मच, today]"
7,"[reddit, users, say, fake, news]","[reddit, user, say, fake, news]","[reddit, user, say, fake, news]"

In [21]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
def lemmatize(words):
    return [lemmatizer.lemmatize(word) for word in words]
df["Lemmatization"] = df["Stopword_Removal"].apply(lemmatize)

df[["Stopword_Removal", "Porter_Stem", "Snowball_Stem", "Lemmatization"]]

,Stopword_Removal,Porter_Stem,Snowball_Stem,Lemmatization
0,"[omg, india, match, today]","[omg, india, match, today]","[omg, india, match, today]","[omg, india, match, today]"
1,"[breaking, news, heavy, rain, mumbai, today]","[break, news, heavi, rain, mumbai, today]","[break, news, heavi, rain, mumbai, today]","[breaking, news, heavy, rain, mumbai, today]"
2,"[म, आज, बहत, खश, ह]","[म, आज, बहत, खश, ह]","[म, आज, बहत, खश, ह]","[म, आज, बहत, खश, ह]"
3,"[movie, awesome]","[movi, awesom]","[movi, awesom]","[movie, awesome]"
4,"[rt, fake, news, spreads, quickly, twitter]","[rt, fake, news, spread, quickli, twitter]","[rt, fake, news, spread, quick, twitter]","[rt, fake, news, spread, quickly, twitter]"
5,"[visit, updates]","[visit, updat]","[visit, updat]","[visit, update]"
6,"[भरत, मच, today]","[भरत, मच, today]","[भरत, मच, today]","[भरत, मच, today]"
7,"[reddit, users, say, fake, news]","[reddit, user, say, fake, news]","[reddit, user, say, fake, news]","[reddit, user, say, fake, news]"

In [22]:
from nltk import pos_tag
def nltk_pos(words):
    return pos_tag(words)
df["NLTK_POS"] = df["Lemmatization"].apply(nltk_pos)
df[["Lemmatization", "NLTK_POS"]]

,Lemmatization,NLTK_POS
0,"[omg, india, match, today]","[(omg, IN), (india, JJ), (match, NN), (today, ..."
1,"[breaking, news, heavy, rain, mumbai, today]","[(breaking, VBG), (news, NN), (heavy, JJ), (ra..."
2,"[म, आज, बहत, खश, ह]","[(म, JJ), (आज, NNP), (बहत, NNP), (खश, NNP), (ह..."
3,"[movie, awesome]","[(movie, NN), (awesome, NN)]"
4,"[rt, fake, news, spread, quickly, twitter]","[(rt, NNS), (fake, VBP), (news, NN), (spread, ..."
5,"[visit, update]","[(visit, NN), (update, NN)]"
6,"[भरत, मच, today]","[(भरत, NN), (मच, NN), (today, NN)]"
7,"[reddit, user, say, fake, news]","[(reddit, NN), (user, NNS), (say, VBP), (fake,..."